### ISSUE TITLE
love.focus does not seem to work on Android

### ISSUE THREAD

**Issue by misha-franz** [MikuAuahDark/livesim3-love#1]
Hi,

I just tried implementing pause on no focus (pressing home button to pause the app).

Found the following thread where somebody claims that love.focus works on Android:

https://love2d.org/forums/viewtopic.php?t=84265

However it does not seem to work for me using your project. Tested on Android 5.1.1 and 9.0.

It does work as expected on Windows, though.

Here is love.focus wiki page.

https://love2d.org/wiki/love.focus

Thanks,
M.

**Comment by MikuAuahDark** [comment]
love.focus in Android is unreliable. It depends on device, Android version,
and ROM used. I'm afraid the problem lies in SDL, not in LOVE, which also
SDL maintainer can't fix.

Pada tanggal Rab, 27 Feb 2019 15.12 misha-franz <notifications@github.com
menulis:

**Comment by MikuAuahDark** [comment]
Closed due to inactivity.
